### ISSUE TITLE
Is this repo actively maintained?

### ISSUE THREAD

**Issue by markc** [dougluce/ident_switch#1]
Hi @dougluce are you actively updating this repo? It seems the roundcube plugin repo is out of date and there is some problem with the original bitbucket repo. I'm looking for an uptodate version that I can perhaps contribute to.

**Comment by dougluce** [comment]
The functionality of this plugin is pretty important to me so I do intend on keeping it in working order. Feel free to send stuff along.

**Comment by markc** [comment]
Ok great. I'll install this version and see if allows me to send via extra ident outgoing settings. I'd like to see another "Secure connection (TLS)" toggle for SMTP as I use 465 by default. Some low hanging fruit would be better instructions in the readme.md.
