### ISSUE TITLE
Proper "Sent Folder"

### ISSUE THREAD

**Issue by maverjk** [dougluce/ident_switch#2]
Hello

I'm testing your plugin in the new roundcube version 1.4.11. Everything works fine but would be really helpful if sent email is going to be stored in the "selected identity" sent folder. Right now it is stored in main identity sent folder.

**Comment by dougluce** [comment]
This is just a Github copy of [Boris Gulay's Bitbucket repo](https://bitbucket.org/BoresExpress/ident_switch). Your request is probably best lodged there.
