### ISSUE TITLE
SQL bug

### ISSUE THREAD

**Issue by NLGBrian** [dougluce/ident_switch#3]
Good evening.

Im trying to install ident switch for roundcube but i get errors.

https://i.imgur.com/h9W9Zvu.png

error while importing: https://i.imgur.com/WFbcd7c.png

The code that must be imported:

CREATE TABLE IF NOT EXISTS ident_switch
(
	id
		int(10) UNSIGNED
		NOT NULL
		AUTO_INCREMENT,
	user_id
		int(10) UNSIGNED
		NOT NULL,
	iid
		int(10) UNSIGNED
		NOT NULL,
	username
		varchar(64),
	password
		varchar(64),
	imap_host
		varchar(64),
	imap_port
		int
		CHECK(imap_port > 0 AND imap_port <= 65535),
    imap_delimiter
        char(1),
	label
		varchar(32),
	flags
		int
		NOT NULL
		DEFAULT 0,
  smtp_host
    varchar(64),
  smtp_port
    int
    CHECK(smtp_port > 0 AND smtp_port <= 65535),
  UNIQUE KEY user_id_label (user_id, label),
  CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_identity_id FOREIGN KEY (iid) REFERENCES identities(identity_id) ON DELETE CASCADE ON UPDATE CASCADE,
  PRIMARY KEY(id),
  INDEX IX_ident_switch_user_id (user_id),
  INDEX IX_ident_switch_iid (iid)
);
can someone advise/help me ? thanks.

**Comment by NLGBrian** [comment]
MySQL 10.5

**Comment by dougluce** [comment]
This is just a Github copy of [Boris Gulay's Bitbucket repo](https://bitbucket.org/BoresExpress/ident_switch). You should probably file a bug there.
