### ISSUE TITLE
Use main account password identity (if ident_switch.password is NULL)

### ISSUE THREAD

**Issue by lota** [dougluce/ident_switch#4]
Thanks  Doug Luce for this great plugin.

I am trying to use a custom installation of Roundcube to create a Mail Archive where users can switch in day-1, day-2, day-3 etc.

All works fine, but seems the "password" of identity should be exist in field "password" table "ident_switch". Unlike "imap_host" field that if NULL use default imap host...

If possible for this plugin use "main account password" if "ident_switch.password=NULL"?

TIA
Alessandro

**Comment by dougluce** [comment]
Thanks but this is just a Github copy of [Boris Gulay's Bitbucket repo](https://bitbucket.org/BoresExpress/ident_switch). You should probably file an issue there.
