### ISSUE TITLE
Folder Refresh and Separator

### ISSUE THREAD

**Issue by MetallianFR68** [dougluce/ident_switch#5]
Hi,

I tried this plugin because several coworkers asked for this function.
It works most of the time and thanks for that great work !

I encounter one problem by one user.
This user has 1000+ imap folders with 3 levels of subfolders.
His imap server as "/" as folder separator

He tries to connect a second IMAP mailbox from another server where the folder separator is "."

We encounter two bugs : 

- when he switches identity, the folder list doesn't refresh. It always keeps the list from the default mailbox. It only refreshes if he goes to PARAMETERS -> FOLDERS

- when he switches back to the main identity, it doesn't refresh aswell. If he goes to PARAMETERS -> FOLDER, it refreshes BUT all folder are listed with any hierarchy. The "/" delimiters obviously isn't taken into account anymore. I think that when the main account has "/" delimiter (which is rare !), the plugin doesn't switch back to "/" when the user select its default account.

ROUNDCUBE 1.4.8 with ident_switch 4.4.1

**Comment by dougluce** [comment]
Hi @MetallianFR68, this site is just a Github mirror of the authoritative site. You may wish to re-open your issue at https://bitbucket.org/BoresExpress/ident_switch/
